### ISSUE TITLE
C source file

### ISSUE THREAD

**Issue by michaelmior** [Ganon-M/ergodox-vim-ubuntu#1]
It would be great if you could share the C source file the firmware is compiled from. I'm wary of just installing a binary I download from GitHub. Assume you're using ErgoDox EZ Configurator, it would also be great to have a link to the layout so it can be easily tweaked.

**Comment by Ganon-M** [comment]
I've added the C firmware source - there is a link in the README to the configurator page for the layout if you want to edit it yourself

**Comment by michaelmior** [comment]
Thanks! Sorry, I must have missed the link in the README earlier.
